# Generated by grokhack.com /forge. Edit freely.
FORGE = {
  "title": "Grok Release Radar",
  "idea": "A daily digest of new releases across Grok integrations",
  "repo_url": "https://github.com/Blockchains/grok-release-radar",
  "default_model": "grok-4.6",
  "window_days": 7,
  "repo_list_url": "https://raw.githubusercontent.com/Blockchains/awesome-grokhack/main/grok-forge.json",
  "repos": [],
  "max_repos": 120,
  "features": {
    "tool_calling": False,
    "live_search": False,
    "structured_output": True,
    "streaming": False,
    "vision": False,
    "scheduled": True
  },
  "system_prompt": "You are the engine of 'Grok Release Radar'. App idea: A daily digest of new releases across Grok integrations. Be accurate, cite sources when you use search, and say clearly when you do not know. You write concise release digests for developers building on Grok and the xAI API."
}
